name: Flask App deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Flask App deploy from NCP server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /usr/local
          sudo rm -rf PhotoClub
          sudo git clone https://github.com/Minku-Koo/PhotoClub.git
          cd PhotoClub
          sudo sed -i 's/\$HOST/"${{ secrets.DB_HOST }}"/' ./utils/db_info.py
          sudo sed -i 's/\$DB_NAME/"${{ secrets.DB_NAME }}"/' ./utils/db_info.py
          sudo sed -i 's/\$PORT/${{ secrets.DB_PORT }}/' ./utils/db_info.py
          sudo sed -i 's/\$USER/"${{ secrets.DB_USERNAME }}"/' ./utils/db_info.py
          sudo sed -i 's/\$PASSWORD/"${{ secrets.DB_PASSWORD }}"/' ./utils/db_info.py
          sudo sed -i 's/\$M_PASSWORD/"${{ secrets.DB_MANAGER_PASSWORD }}"/' ./utils/db_info.py
          sudo pip3 install -r requirment.txt
          sudo systemctl restart pclub
